- name: Create hpccloud user
  become: yes
  become_user: root
  user: name=hpccloud shell=/bin/bash uid=1002
  tags: users

- name: Get ubuntu user authorized_keys
  become: yes
  become_user: root
  command: cat /home/{{ default_user }}/.ssh/authorized_keys
  register: ubuntu_public_key

- name: Copy ubuntu user authorized_keys
  authorized_key: user=hpccloud
                  key="{{ ubuntu_public_key.stdout }}"

- name: Give hpccloud passwordless sudo
  become: yes
  become_user: root
  lineinfile: "dest=/etc/sudoers state=present regexp='^hpccloud' line='hpccloud ALL=(ALL) NOPASSWD: ALL'"
  tags: users

- name: Add authorized keys for hpccloud
  become: yes
  become_user: root
  authorized_key: user=hpccloud
                  key="{{ lookup('file', item)}}"
  with_fileglob:
    - ../public_keys/*
  tags: users
