- name: Create hpccloud user
  user: name=hpccloud shell=/bin/bash
  tags: users
  sudo: yes

- name: Get ubuntu user authorized_keys
  command: cat /home/{{ default_user }}/.ssh/authorized_keys
  register: ubuntu_public_key

- name: Copy ubuntu user authorized_keys
  authorized_key: user=hpccloud
                  key="{{ ubuntu_public_key.stdout }}"
  sudo: yes


- name: Give hpccloud passwordless sudo
  lineinfile: "dest=/etc/sudoers state=present regexp='^hpccloud' line='hpccloud ALL=(ALL) NOPASSWD: ALL'"
  tags: users
  sudo: yes

- name: Add authorized keys for hpccloud
  sudo: yes
  authorized_key: user=hpccloud
                  key="{{ lookup('file', item)}}"
  with_fileglob:
    - ../public_keys/*
  tags: users
