- name: Create application base directory
  become_user: root
  file: dest=/opt/hpccloud mode=755 owner=hpccloud group=hpccloud state=directory
  tags:
       - common

- name: Add node PPA key
  command: "apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 68576280"
  become: yes
  become_user: root

- name: Add node PPA
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main"
  become: yes
  become_user: root

- name: Update apt cache
  apt: update_cache=yes
  become_user: root

- name: Install Python, git and nodejs
  apt: name={{ item }} state=present
  become_user: root
  with_items:
    - python-dev
    - git
    - nodejs

- name: Update npm
  command: "npm install -g npm@3"
  become: yes
  become_user: root

- name: Download pip setup
  become_user: root
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=.

- name: Install pip
  become_user: root
  command: python get-pip.py
