- name: Create application base directory
  sudo: yes
  file: dest=/opt/hpccloud mode=755 owner=websimdev group=websimdev state=directory
  tags:
       - common

- name: Add nodejs ppa
  apt_repository: repo='ppa:chris-lea/node.js' update_cache=no
  sudo: yes

- name: Update apt cache
  apt: update_cache=yes
  sudo: yes

- name: Install Python, git and nodejs
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - python-dev
    - git
    - nodejs

- name: Download pip setup
  sudo: yes
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=.

- name: Install pip
  sudo: yes
  command: python get-pip.py
