- name: Install rabbitmq
  become: yes
  become_user: root
  apt: name=rabbitmq-server state=present
  tags: rabbit

- name: Enable rabbitmq-server to survive reboot
  service: name=rabbitmq-server enabled=yes
  become: yes
  become_user: root
  tags: rabbit
