- name: Install rabbitmq
  become_user: root
  apt: name=rabbitmq-server state=present
  tags: rabbit

- name: Enable rabbitmq-server to survive reboot
  service:
    name=rabbitmq-server
    enabled=yes
    state=restarted
  become_user: root
  tags: rabbit
