- name: Delete default guest user
  become: yes
  become_user: root
  rabbitmq_user:
    user: guest
    state: absent

- name: Create admin account with access to everything
  become: yes
  become_user: root
  rabbitmq_user:
    user: "{{ rabbitmq_admin_user }}"
    password: "{{ rabbitmq_admin_password }}"
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present

- name: Create rabbitmq.config
  become: yes
  become_user: root
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
    owner: root
    group: root
    mode: 0644

- name: Create /celery vhost
  become: yes
  become_user: root
  rabbitmq_vhost:
    name: /celery
    state: present

- name: Create celery user with access to /celery
  become: yes
  become_user: root
  rabbitmq_user:
    user: "{{ rabbitmq_celery_user }}"
    password: "{{ rabbitmq_celery_password }}"
    vhost: /celery
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- name: Restart RabbitMQ for changes to take effect
  become: yes
  become_user: root
  service:
    name: rabbitmq-server
    state: restarted
