- name: Create ParaView directory
  sudo: yes
  file: dest=/opt/websim/paraview mode=755 owner=websimdev group=websimdev state=directory
  tags: paraview

- name: Install ParaView build prerequisities
  sudo: yes
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - cmake
    - cmake-curses-gui
    - libnetcdf-dev
    - libhdf5-dev
  tags: paraview

- name: Get ParaView from github
  git: repo=https://github.com/Kitware/ParaView.git version=v4.2.0 dest=/opt/websim/paraview/src
  tags: paraview

- name: Create ParaView build directory
  sudo: yes
  file: dest=/opt/websim/paraview/build mode=755 owner=websimdev group=websimdev state=directory
  tags: paraview

- name: Create ParaView install directory
  sudo: yes
  file: dest=/opt/websim/paraview/install mode=755 owner=websimdev group=websimdev state=directory
  tags: paraview

- name: Create script to build ParaView
  action: template src=build.sh.j2 dest=/opt/websim/paraview/build/build.sh mode=700 owner=websimdev
  tags: paraview

- name: Build ParaView
  shell: /opt/websim/paraview/build/build.sh chdir=/opt/websim/paraview/build
  tags: paraview

- name: Install ParaView
  command: make install chdir=/opt/websim/paraview/build
  tags: paraview
