- name: Create ParaView directory
  become: yes
  become_user: root
  file: dest=/opt/hpccloud/paraview mode=755 owner=hpccloud group=hpccloud state=directory
  tags: paraview

- name: Install ParaView build prerequisities
  become: yes
  become_user: root
  apt: name={{ item }} state=present
  with_items:
    - cmake
    - cmake-curses-gui
    - libnetcdf-dev
    - libhdf5-dev
  tags: paraview

- name: Get ParaView from github
  git: repo=https://github.com/Kitware/ParaView.git version={{paraview_version}} dest=/opt/hpccloud/paraview/src accept_hostkey=yes
  tags: paraview

- name: Create ParaView build directory
  become: yes
  become_user: root
  file: dest=/opt/hpccloud/paraview/build mode=755 owner=hpccloud group=hpccloud state=directory
  tags: paraview

- name: Create ParaView install directory
  become: yes
  become_user: root
  file: dest=/opt/hpccloud/paraview/install mode=755 owner=hpccloud group=hpccloud state=directory
  tags: paraview

- name: Create script to build ParaView
  action: template src=build.sh.j2 dest=/opt/hpccloud/paraview/build/build.sh mode=700 owner=hpccloud
  tags: paraview

- name: Build ParaView
  shell: /opt/hpccloud/paraview/build/build.sh chdir=/opt/hpccloud/paraview/build
  tags: paraview

- name: Install ParaView
  command: make install chdir=/opt/hpccloud/paraview/build
  tags: paraview
