- name: probe cumulus folder
  stat: path=/opt/hpccloud/cumulus
  register: path
  tags: cumulus

- name: Get cumulus from github
  git: repo=https://github.com/Kitware/cumulus.git version={{ cumulus_version }} dest=/opt/hpccloud/cumulus force=yes accept_hostkey=yes
  become_user: root
  when: path.stat.exists == False or not development
  tags: cumulus

- name: Install system dependencies
  apt: name="{{ item }}" state=present
  with_items:
    - libffi-dev
    - libssl-dev
    - openssl
  become: yes
  become_user: root

- name: Install cumulus dependencies
  pip: requirements=/opt/hpccloud/cumulus/requirements.txt
  become_user: root
  tags: cumulus

- name: Create celery user (need to create so we can assign read permission to the cumulus config file)
  user: name=celery shell=/bin/bash state=present
  become_user: root
  tags: celery

- name: Change owner of cumulus directory
  file: dest=/opt/hpccloud/cumulus mode=775 owner=hpccloud group=celery state=directory recurse=true
  become_user: root
  tags: cumulus

- name: Tell git to ignore permission changes
  command: git config --replace-all core.filemode false chdir=/opt/hpccloud/cumulus
  tags: cumulus

- name: Get AMIs from EC2
  command: python roles/cumulus/files/amis.py {{ aws_access_key_id }} {{ aws_secret_access_key }} us-west-2
  when: aws_access_key_id != "" and aws_secret_access_key != ""
  register: get_amis
  delegate_to: 127.0.0.1
  tags:
    - cumulus
    - update_ips


- name: Get EC2 instances private IP
  local_action: command python roles/cumulus/files/ec2_private_ip.py {{ aws_access_key_id }} {{ aws_secret_access_key }} us-west-2 {{ groups['girder'][0] }}
  when: aws_access_key_id != "" and aws_secret_access_key != ""
  register: get_private_ip
  become: no
  tags:
    - cumulus
    - update_ips

- name: Create keys directory
  file: dest={{ keys_directory }} mode=750 owner=celery group=celery state=directory
  become_user: root
  tags: cumulus

- name: Get local host name, used in Vagrant deployment
  local_action: command hostname
  become: no
  register: local_hostname
  tags:
    - cumulus
    - update_ips

- name: Create config.json
  action: template src=config.json.j2 dest=/opt/hpccloud/cumulus/cumulus/conf/config.json mode=640 owner=hpccloud group=celery
  tags:
    - cumulus
    - update_ips
  become_user: root

- name: Install cumulus
  pip:
    chdir: /opt/hpccloud/cumulus
    name: .
    extra_args: "--user -I"
  become_user: hpccloud
  when: development == False
  tags: cumulus

- name: Install cumulus (Development)
  pip:
    chdir: /opt/hpccloud/cumulus
    name: .
    extra_args: "-e"
  become_user: root
  when: development
  tags: cumulus
