- name: Get cumulus from github
  git: repo=https://github.com/cjh1/cumulus.git version={{ cumulus_version }} dest=/opt/websim/cumulus
  sudo: yes
  tags: cumulus

- name: Install specified python requirements.
  pip: requirements=/opt/websim/cumulus/requirements.txt
  sudo: yes
  tags: cumulus

- name: Create celery user (need to create so we can assign read permission to the cumulus config file)
  user: name=celery shell=/bin/bash state=present
  sudo: yes
  tags: celery

- name: Change owner of cumulus directory
  file: dest=/opt/websim/cumulus mode=775 owner=websimdev group=celery state=directory recurse=true
  sudo: yes
  tags: cumulus

- name: Tell git to ignore permission changes
  command: git config core.filemode false chdir=/opt/websim/cumulus
  tags: cumulus

- name: Create config.json
  action: template src=config.json.j2 dest=/opt/websim/cumulus/config.json mode=640 owner=websimdev group=celery
  tags: cumulus
  sudo: yes

- name: Create keys directory
  file: dest={{ keys_directory }} mode=700 owner=celery group=celery state=directory
  sudo: yes
  tags: cumulus

- name: Copy over private key
  sudo: yes
  copy: src={{ private_key_path }} dest={{ keys_directory }}/{{ private_key }} mode=400 owner=celery group=celery
  tags: cumulus
