- name: Get cumulus from github
  git: repo=https://github.com/cjh1/cumulus.git version={{ cumulus_version }} dest=/opt/websim/cumulus
  sudo: yes

- name: Install specified python requirements.
  pip: requirements=/opt/websim/cumulus/requirements.txt
  sudo: yes

- name: Change owner of cumulus directory
  file: dest=/opt/websim/cumulus mode=755 owner=websimdev group=websimdev state=directory recurse=true
  sudo: yes
