- name: Get cumulus from github
  git: repo=https://github.com/Kitware/cumulus.git version={{ cumulus_version }} dest=/opt/hpccloud/cumulus force=yes accept_hostkey=yes
  sudo: yes
  tags: cumulus

- name: Install specified python requirements.
  pip: requirements=/opt/hpccloud/cumulus/requirements.txt
  sudo: yes
  tags: cumulus

- name: Create celery user (need to create so we can assign read permission to the cumulus config file)
  user: name=celery shell=/bin/bash state=present
  sudo: yes
  tags: celery

- name: Change owner of cumulus directory
  file: dest=/opt/hpccloud/cumulus mode=775 owner=websimdev group=celery state=directory recurse=true
  sudo: yes
  tags: cumulus

- name: Tell git to ignore permission changes
  command: git config core.filemode false chdir=/opt/hpccloud/cumulus
  tags: cumulus

- name: Get AMIs from EC2
  command: python roles/cumulus/files/amis.py {{ aws_access_key_id }} {{ aws_secret_access_key }} us-west-2
  when: aws_access_key_id != "" and aws_secret_access_key != ""
  register: get_amis
  delegate_to: 127.0.0.1
  tags:
    - cumulus
    - update_ips


- name: Get EC2 instances private IP
  local_action: command python roles/cumulus/files/ec2_private_ip.py {{ aws_access_key_id }} {{ aws_secret_access_key }} us-west-2 {{ groups['girder'][0] }}
  when: aws_access_key_id != "" and aws_secret_access_key != ""
  register: get_private_ip
  tags:
    - cumulus
    - update_ips

- name: Create keys directory
  file: dest={{ keys_directory }} mode=700 owner=celery group=celery state=directory
  sudo: yes
  tags: cumulus

- name: Get local host name, used in Vagrant deployment
  local_action: command hostname
  register: local_hostname
  tags:
    - cumulus
    - update_ips

- name: Create config.json
  action: template src=config.json.j2 dest=/opt/hpccloud/cumulus/config.json mode=640 owner=websimdev group=celery
  tags:
    - cumulus
    - update_ips
  sudo: yes
