

- name: Install pip3
  apt: name={{ item }} state=present
  become: yes
  become_user: root
  with_items:
    - python3-pip
  tags:
    - pyfr

- name: Install required native libs
  apt: name={{ item }} state=present
  become: yes
  become_user: root
  with_items:
    - libhdf5-dev
    - cython3
    - libmpich-dev
    - libmetis-dev
  tags:
    - pyfr

- name: Install PyFR required packages
  pip: executable=pip3  name={{item.package}} version={{item.version}} state=present
  become: yes
  become_user: root
  with_items:
    - {package: 'numpy', version: 1.8}
    - {package: 'six', version: 1.8.0}
  tags: pyfr

- name: Install PyFR from GitHub
  pip: executable=pip3 name="git+https://github.com/vincentlab/PyFR.git@v1.3.0#egg=pyfr" state=present editable=False
  become: yes
  become_user: root
  tags: pyfr
