- name: Add Xorg ppa
  apt_repository: repo='ppa:xorg-edgers/ppa' update_cache=yes
  tags: osmesa
  become_user: root

- name: Install Mesa build deps
  command: apt-get -y build-dep mesa
  become_user: root
  tags: osmesa

- name: Install dependencies
  apt: name={{ item }} state=present
  become_user: root
  with_items:
    - build-essential
    - llvm-dev
    - libdrm2
  tags: osmesa

- name: Create OSMesa directory
  become_user: root
  file: dest=/opt/hpccloud/osmesa mode=755 owner=hpccloud group=hpccloud state=directory
  tags: osmesa

- name: Get Mesa from repo
  git: repo=git://anongit.freedesktop.org/git/mesa/mesa version=mesa-10.2.5 dest=/opt/hpccloud/osmesa/src accept_hostkey=yes
  tags: osmesa

- name: Create script to build Mesa
  action: template src=build.sh.j2 dest=/opt/hpccloud/osmesa/src/build.sh mode=700 owner=hpccloud
  tags: osmesa

- name: Build Mesa
  shell: /opt/hpccloud/osmesa/src/build.sh chdir=/opt/hpccloud/osmesa/src
  tags: osmesa

- name: Install Mesa
  command: make install chdir=/opt/hpccloud/osmesa/src
  become_user: root
  tags: osmesa
