- name: Template launcher config
  become: yes
  become_user: root
  action: template src=launcher.json.j2 dest=/etc/default/pvwlauncher mode=644 owner=root
  tags:
    - pvwlauncher
    - update_ips

- name: Install launcher as service
  copy: src=../files/pvwlauncher.conf dest=/etc/init/pvwlauncher.conf mode=644 owner=root
  become: yes
  become_user: root
  tags: pvwlauncher
