- name: Create users
  hosts: all
  user: ubuntu
  roles:
    - users

- name: Common configuration
  hosts: all
  user: websimdev
  roles:
    - common

- name: Set up rabbitmq
  hosts: cumulus
  user: websimdev
  roles:
    - rabbitmq

- name: Setup cumulus
  hosts: cumulus
  user: websimdev
  roles:
    - cumulus

- name: Set up ParaView
  hosts: paraview
  user: websimdev
  roles:
    - osmesa
    - paraview

- name: Set up moab reader
  hosts: paraview
  user: websimdev
  roles:
    - moab
    - moabreader

- name: Setup Girder
  hosts: girder
  user: websimdev
  roles:
    - girder

- name: Set up celery
  hosts: cumulus
  user: websimdev
  roles:
    - celery

- name: Set up hpccloud
  hosts: hpccloud
  user: websimdev
  roles:
    - hpccloud

- name: Set up ParaViewWeb launcher
  hosts: hpccloud
  user: websimdev
  roles:
    - pvwlauncher


