- name:
  hosts: all
  vars:
    required_ansible_version: 2.0.2
  tasks:
  - fail: msg="Playbook requires ansible >= {{required_ansible_version}}"
    when: ansible_version.string|version_compare(required_ansible_version, '<')

- name: Create demo user
  hosts: users
  become: yes
  become_user: hpccloud
  roles:
    - users

- name: Install PyFR
  hosts: pyfr
  become: yes
  become_user: hpccloud
  roles:
    - pyfr

- name: Install ParaView
  hosts: paraview
  become: yes
  become_user: hpccloud
  roles:
    - paraview

- name: Create HPCCloud demo cluster
  hosts: fixtures
  become: yes
  become_user: hpccloud
  roles:
    - fixtures
