- name: Create moab directory
  sudo: yes
  file: dest=/opt/hpccloud/moab mode=755 owner=hpccloud group=hpccloud state=directory
  tags: moab

- name: Install moab build prerequisities
  sudo: yes
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - cmake
    - cmake-curses-gui
    - libnetcdf-dev
    - libhdf5-dev
  tags: moab

- name: Get moab from github
  git: repo=https://github.com/judajake/moab.git version=624c4e95ad1e935a7937a1b10bf252632d4496d1 dest=/opt/hpccloud/moab/src accept_hostkey=yes
  tags: moab

- name: Create moab build directory
  sudo: yes
  file: dest=/opt/hpccloud/moab/build mode=755 owner=hpccloud group=hpccloud state=directory
  tags: moab

- name: Create moab install directory
  sudo: yes
  file: dest=/opt/hpccloud/moab/install mode=755 owner=hpccloud group=hpccloud state=directory
  tags: moab

- name: Create script to build moab
  action: template src=build.sh.j2 dest=/opt/hpccloud/moab/build/build.sh mode=700 owner=hpccloud
  tags: moab

- name: Build moab
  shell: /opt/hpccloud/moab/build/build.sh chdir=/opt/hpccloud/moab/build
  tags: moab

- name: Install moab
  command: make install chdir=/opt/hpccloud/moab/build
  tags: moab
