- name: probe hpccloud folder
  stat: path=/opt/hpccloud/hpccloud
  register: path
  tags: hpccloud

- name: Get hpccloud from github
  git: repo=https://github.com/Kitware/HPCCloud.git version={{ hpccloud_version }} dest=/opt/hpccloud/hpccloud force=yes accept_hostkey=yes
  become_user: root
  when: path.stat.exists == False
  tags: hpccloud

- name: Install hpccloud Python dependencies
  pip: requirements=/opt/hpccloud/hpccloud/requirements.txt
  become_user: root
  tags: hpccloud

- name: Make sure we have the right version of npm
  npm: name=npm version=2.1.5 global=yes
  tags: hpccloud
  become_user: root

- name: Install n to upgrade node
  npm: name=n global=yes
  tags: hpccloud
  become_user: root

- name: Install right version of node
  command: n 0.12.9
  tags: hpccloud
  become_user: root

- name: Change owner of hpccloud directory
  file: dest=/opt/hpccloud/hpccloud mode=755 owner=hpccloud group=hpccloud state=directory recurse=true
  become_user: root
  tags: hpccloud
  when: not development

- name: Tell git to ignore permission changes
  command: git config core.filemode false chdir=/opt/hpccloud/hpccloud
  tags: hpccloud
  when: not development

- name: Run npm install
  npm: path=/opt/hpccloud/hpccloud
  tags: hpccloud

- name: Run npm run build
  command: npm run build:release chdir=/opt/hpccloud/hpccloud
  tags: hpccloud

- name: Install apache
  apt: name=apache2 state=present
  become_user: root
  tags:
    - apache
    - hpccloud

- name: Enable mod_proxy
  apache2_module: state=present name=proxy
  tags:
    - apache
    - hpccloud
  become_user: root

- name: Enable mod_rewrite
  apache2_module: state=present name=rewrite
  tags:
    - apache
    - hpccloud
  become_user: root

- name: Enable mod_proxy_http
  apache2_module: state=present name=proxy_http
  tags:
    - apache
    - hpccloud
  become_user: root
  notify:
    - restart apache2

- name: Enable mod_proxy_wstunnel
  apache2_module: state=present name=proxy_wstunnel
  tags:
  - apache
  - hpccloud
  become_user: root
  notify:
    - restart apache2

- name: Create proxy mapping file
  become_user: root
  file: dest=/opt/hpccloud/proxy.db mode=640 owner=hpccloud group=www-data state=touch
  tags:
    - apache
    - hpccloud

- name: Create local proxy mapping file
  become_user: root
  file: dest=/opt/hpccloud/proxy.txt mode=640 owner=hpccloud group=www-data state=touch
  tags:
    - apache

- name: Disable the default site
  action: command a2dissite 000-default removes=/etc/apache2/sites-enabled/000-default.conf
  tags:
    - apache
    - hpccloud
  become_user: root
  notify:
    - restart apache2


- name: Copy over config
  copy: src=../files/hpccloud.conf dest=/etc/apache2/sites-available/hpccloud.conf mode=644 owner=root
  tags: apache
  become_user: root
  notify:
    - restart apache2

- name: Enable cmd-web site
  action: command a2ensite hpccloud  creates=/etc/apache2/sites-enabled/hpccloud.conf
  tags: apache
  become_user: root
  notify:
    - restart apache2

- name: Update directory
  replace:
    dest: /etc/apache2/apache2.conf
    regexp: '^<Directory /var/www/>$'
    replace: '<Directory /opt/hpccloud/hpccloud/dist/>'
  tags:
    - apache
    - hpccloud
  become_user: root
  notify:
    - restart apache2
